function(find_directories_containing varname pattern)
    file(GLOB_RECURSE FILES "${pattern}")
    set(result "")
    foreach (it ${FILES})
        get_filename_component(_dir ${it} PATH)
        list(APPEND result ${_dir})
    endforeach ()
    list(REMOVE_DUPLICATES result)
    set(${varname} "${result}" PARENT_SCOPE)
endfunction()
